apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm
  namespace: smartllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      containers:
      - name: litellm
        image: ghcr.io/berriai/litellm:main-latest
        imagePullPolicy: IfNotPresent
        args:
        - --config
        - /app/config.yaml
        - --port
        - "4000"
        - --detailed_debug
        env:
        - name: LITELLM_CUSTOM_LOGGER
          value: /app/logger.py
        - name: PYTHONPATH
          value: /app
        - name: COLLECTOR_URL
          value: "http://tineye.tineye.svc.cluster.local:8889/log"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: DATABASE_URL
          value: "postgresql://litellm:$(POSTGRES_PASSWORD)@postgres.smartllm.svc.cluster.local:5432/litellm"
        ports:
        - containerPort: 4000
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
          limits:
            memory: 2Gi
        volumeMounts:
        - name: config
          mountPath: /app/config.yaml
          subPath: config.yaml
        - name: logs
          mountPath: /logs
        - name: logger
          mountPath: /app/logger.py
          subPath: logger.py
      volumes:
      - name: config
        configMap:
          name: litellm-config
      - name: logs
        persistentVolumeClaim:
          claimName: litellm-logs-pvc
      - name: logger
        configMap:
          name: litellm-logger
---
apiVersion: v1
kind: Service
metadata:
  name: litellm
  namespace: smartllm
spec:
  selector:
    app: litellm
  ports:
  - port: 4000
    targetPort: 4000
