apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: litellm-logs-pvc
  namespace: litellm
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: litellm
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
